version: 0.0
os: linux
file_exists_behavior: OVERWRITE

files:
  - source: .
    destination: /opt/backend

permissions:
  - object: /opt/backend
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  AfterInstall:
    - location: scripts/backend_after_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/backend_start.sh
      timeout: 300
      runas: ec2-user
