version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build --if-present

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - package.json
    - package-lock.json
    - index.js
    - dist/**/*
