version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  post_build:
    commands:
      - aws ssm send-command \
        --document-name "AWS-RunShellScript" \
        --targets "Key=tag:Name,Values=backend-private-ec2" \
        --parameters 'commands=[
          "mkdir -p /home/ubuntu/app",
          "cp -r . /home/ubuntu/app",
          "npm install",
          "pm2 restart all || pm2 start index.js --name backend"
        ]'
